webhooks:
# add your discord webhook link here

logged-events:
  - player-command-execution
  - console-command-execution
  - player-join
  - player-disconnect
  - player-kick
  - player-death
  - player-respawn
  - player-kill-entity
  - player-kill-named-entity

# Backtick characters (`) have to be escaped using a double backtick (``)
# A single backtick can be used to escape an embedded argument, eg. `#{command}
messages:
  player-command: "Player **#{player}** executed the command ``#{command}``"
  console-command: "CONSOLE executed the command ``#{command}``"
  player-join: "Player **#{player}** joined the server!"
  player-disconnect: "Player **#{player}** disconnected from the server."
  player-kick: "Player **#{player}** was kicked from the server!"
  player-death: "Player **#{player}** died!"
  player-respawn: "Player **#{player}** respawned."
  player-kill-entity: "Player **#{player}** killed entity of type **#{type}**"
  player-kill-named-entity: "Player **#{player}** killed entity of type **#{type}**, named **#{name}**"